### ISSUE TITLE
External trigger to full screen

### ISSUE THREAD

**Issue by AbysFlo** [VLZH/react-lightgallery#14]
Hi there, I have been trying to find a way to trigger the gallery into fullscreen without clicking on the thumbnails. 

Basically I'm trying to decouple react-slick with lightgallery. Clicking on a picture on react-slick would open the gallery into full screen. So far I'm just able to show and hide those thumbnails but can't find a way to bypass clicking on them!

Any hint if doable? Found some material with Jquery, not sure that would be the best solution though.

**Comment by hieusmiths** [comment]
I can not find any prop for it 🥇

**Comment by VLZH** [comment]
@AbysFlo @hieusmiths Hello everybody!) I have implemented new features in version `0.8.1`. Documentation for new features: 
- [useLightgallery](https://github.com/VLZH/react-lightgallery#uselightgallery)
- [withLightgallery](https://github.com/VLZH/react-lightgallery#uselightgallery)

P.S I am sorry for so long time to reply on this issue.
