### ISSUE TITLE
OnClick PhotoItem always opens the first photo

### ISSUE THREAD

**Issue by vhelke** [VLZH/react-lightgallery#17]
Hi,

Thanks for the nice wrapper! Good work!

For me it looks like the first photo in the gallery is always opened, even if I make onClick event to some other photo. I tested also on the example, and the same problem there.

**Comment by VLZH** [comment]
@vhelke Thank you for your issue. I fixing it right now.

**Comment by VLZH** [comment]
@vhelke This bug was fixed in 0.9.0 version
