### ISSUE TITLE
How i can destroy lightgallery on componentWillUnmount?

### ISSUE THREAD

**Issue by vitalikbodnar** [VLZH/react-lightgallery#2]
this is my code. How i can destroy lightgallery on componentWillUnmount?

    constructor(props) {
        super(props);
    };

    toggleLikeHandler = (status) => () => {
        this.props.toggleLike({data: {post_id: this.props.article.id, user_id: this.props.userId}, status});
    };

    componentWillUnmount() {

    }

    render() {
        const {article} = this.props;
        let status = false;
        let img;
        article.likes.items.map(elem => {
            if (elem.user_id === this.props.userId) {
                status = elem.id;
            }
        });

        if (article.files[0]) {
            img = article.files.map(elem => {
                return `${BACKEND_ROOT}${elem.path}`;
            });
        }
        return (
            <article className="blog blog-single-post col-sm-12">
                <h3 className="blog-title singlepost-title">{article.name}</h3>
                <div className="blog-info clearfix">
                    <div className="post-left">
                        <div className="post-left-wrapper">
                            <div className="post-author-img">
                                <Link to={{pathname: "/users/" + article.author.id}}>
                                    <img className="avatar" src={article.author.avatar} alt=""/>
                                </Link>
                            </div>
                            <ul>
                                <li>
                                    <a href="#"><span
                                        className="time">{transformDate(article.created_at.date)}</span></a>
                                </li>
                                <li>
                                    <Link to={{pathname: "/users/" + article.author.id}} className="pull-left">
                                        <span className="name">{article.author.name} {article.author.surname}</span>
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div className="post-right post-left">
                        <ul>
                            <li>
                                <a><i className={status ? 'fa fa-heart' : 'fa fa-heart-o'} aria-hidden="true"
                                      style={{marginTop: '1px'}}/>{article.likes.count}</a>
                            </li>
                            <li>
                                <a><img alt="" src="/light/assets/img/eye.png"
                                        style={{marginTop: '-2px', marginRight: '5px'}}/>{article.views.count}</a>
                            </li>
                            <li>
                                <a><i className="fa fa-comment-o" aria-hidden="true"/>{article.comments.count}</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="blog-content-wrapper">
                    <div className="blog-content-wrapper-left col-sm-8">
                        {img ?
                            <div className="blog-image">
                                <LightgalleryProvider>
                                {
                                    img.map((img, index) => {
                                        return (
                                            <PhotoItem key={index} image={img}/>
                                        )
                                    })
                                }
                                </LightgalleryProvider>
                            </div>
                            : null}

                        <div className="blog-content">
                            {ReactHtmlParser(article.content)}
                            <div className="big-like-wrap">
                                <div className="text">Liked This Article?</div>
                                <div className="like-circle" onClick={this.toggleLikeHandler(status)}>
                                    <i className={status ? 'fa fa-heart' : 'fa fa-heart-o'} aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    {this.props.children}
                </div>
            </article>
        );
    }

**Comment by VLZH** [comment]
@vitalikbodnar Hello! Thank you for this issue.
I meant that LightgalleryProvider will be added once on a page. And you have a mechanism of groups for grouping LightgalleryItem`s
But I find some problem with a little memory leak. I will fix this problem this week.

**Comment by vitalikbodnar** [comment]
> @vitalikbodnar Hello! Thank you for this issue.
> I meant that LightgalleryProvider will be added once on a page. And you have a mechanism of groups for grouping LightgalleryItem`s
> But I find some problem with a little memory leak. I will fix this problem this week.

Thank you for your reply!

**Comment by asilvestre87** [comment]
> 
> 
> @vitalikbodnar Hello! Thank you for this issue.
> I meant that LightgalleryProvider will be added once on a page. And you have a mechanism of groups for grouping LightgalleryItem`s
> But I find some problem with a little memory leak. I will fix this problem this week.

Hi @VLZH, did you fix the problem?

**Comment by crestwebmob** [comment]
Hello @VLZH
Did this issue has been fixed?

**Comment by VLZH** [comment]
Hello @crestwebmob! Sorry for so long answer.
According to my latest measurements, there is no leak.
Lightgallery will be destroyed on each close of gallery.

**Comment by shafayet2368** [comment]
Hi @VLZH , the gallery still keeps the old data on closing. When I open the gallery with different images , it still keeps the previous images. How can I solve this problem. Is there any method to access the destroy() method ..??

**Comment by VLZH** [comment]
@shafayet2368 Can you to send example? Because a gallery destroying on each close

**Comment by shafayet2368** [comment]
```
<LightgalleryProvider>
  {items.map((item) => {
    return <PhotoItem group="group" item={item} />;
  })}
</LightgalleryProvider>
```
This is a code structure that I am using. It keeps the previous images as the LightgalleryProvider is never Unmounted.

**Comment by shadowreplicant** [comment]
@VLZH
I added react-router-dom, here is [codesandbox](https://codesandbox.io/s/react-lightgallery1-o3v4x?fontsize=14&hidenavigation=1&theme=dark) based on your example

Open console, click to link "Other" and you will see error:
`proxyConsole.js:64 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t (at src/index.js:30)
    in App (created by Context.Consumer)
`
unfortunately, I don't know so well react, but seems that everything is still working

**Comment by shadowreplicant** [comment]
@VLZH
I added react-router-dom, here is [codesandbox](https://codesandbox.io/s/react-lightgallery1-o3v4x?fontsize=14&hidenavigation=1&theme=dark) based on your example

Open console, click to link "Other" and you will see error:
`proxyConsole.js:64 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t (at src/index.js:30)
    in App (created by Context.Consumer)
`
unfortunately, I don't know so well react, but seems that everything is still working
