### ISSUE TITLE
Is there an api for lightgallery events? 

### ISSUE THREAD

**Issue by verticalgrain** [VLZH/react-lightgallery#8]
Hi, thanks for this great port of lightgallery. 

I'm wondering if it's possible to access lightgallery events?

**Comment by VLZH** [comment]
Hello! Thanks!
I will add methods for access to events. I think in 1 day - maybe sooner.

**Comment by verticalgrain** [comment]
Thanks for the super fast response @VLZH !

**Comment by VLZH** [comment]
@verticalgrain Hello! Sorry for so long answer(this message). I added new props and maybe i will add props for LightgalleryItem for access to events specific each slide.

**Comment by verticalgrain** [comment]
> @verticalgrain Hello! Sorry for so long answer(this message). I added new props and maybe i will add props for LightgalleryItem for access to events specific each slide.

@VLZH Thank you for adding these features so quickly. Your work is greatly appreciated. I will give the events a try and let you know if I have any questions.
