### ISSUE TITLE
image lazy loading is broken when use with thumbnail plugin

### ISSUE THREAD

**Issue by shadowreplicant** [VLZH/react-lightgallery#9]
https://github.com/VLZH/react-lightgallery/blob/f844b9f68e6b3ca74963114791bcc2c9e5478bc3/src/LightgalleryItem.js#L36
src and thumb are the same => thumbnail plugin will use scaled full images to create its thumbs => it will load full list of images.

May be use different property for thumb?
`thumb: this.props.thumb || this.props.src`

workaround with extend:
```
export class LightgalleryItemWithThumbs extends LightgalleryItem {
    register = () => {
        this.context.registerPhoto(this.state.id, this.props.group, {
            src: this.props.src,
            thumb: this.props.thumb || this.props.src,
            subHtml: this.props.subHtml || "",
            downloadUrl: this.props.downloadUrl || ""
        });
    };
}
```

**Comment by VLZH** [comment]
@shadowreplicant Thank you for this issue! You were absolutely right; Version with fix: [0.6.1](https://yarnpkg.com/en/package/react-lightgallery)
